server {
    listen 80 default_server;
    server_name _;

    location /dev-infra-backup/ {
        alias /var/www/dev-infra-backup/;
        autoindex on;
        auth_basic "dev-infra";
        auth_basic_user_file /etc/nginx/.htpasswd;
    }

    location / {
        return 404;
    }
}
