listen=YES
listen_ipv6=NO
anonymous_enable=YES
anon_root=/srv/ftp
no_anon_password=YES
anon_upload_enable=NO
anon_mkdir_write_enable=NO
anon_other_write_enable=NO
local_enable=NO
write_enable=NO
dirmessage_enable=YES
xferlog_enable=YES
connect_from_port_20=YES
pasv_enable=YES
pasv_min_port=30000
pasv_max_port=30009
pasv_address=127.0.0.1
seccomp_sandbox=NO
